exit
ls
vi config.prop
./storage_checker.sh replication
./storage_checker.sh replication
ls
vi config.prop 
./storage_checker.sh replication
vi storage_checker.sh 
vi storage_checker.sh
ls
vi config.prop 
vi storage_checker.sh
./storage_checker.sh replication
./storage_checker.sh replication
vi submitter.sh 
./storage_checker.sh replication
./storage_checker.sh replication
ls
vi config.prop 
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
vi config.prop 
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
vi config.prop 
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
vi config.prop
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
./storage_checker.sh replication
vi config.prop 
./storage_checker.sh replication
vi config.prop 
./storage_checker.sh replication
./storage_checker.sh sharding
./storage_checker.sh sharding
